### ISSUE TITLE
Layout problems on mobile

### ISSUE THREAD

**Issue by NikolausDemmel** [ros-infrastructure/answers.ros.org#87]
The forum has layout problems on mobile devices it seems (at least on my Nexus 4). 

The page width seems to be fixed to something wider than my screen, and at the same time I don't seem to be able to zoom in or out of the page, necessitating frequent left-right scrolling when reding questions/answers/comments.

Moreover some information is not being displayed, like the author of questions/answers/comments with not obvious way to get to that info at all.

**Comment by martimorta** [comment]
For me the biggest problem is not be able to see the author, making a computer necessary to delete spam(mers).
This is an image of my Nexus 4 (2 joined screenshots)
![ros_answers_nexus4](https://cloud.githubusercontent.com/assets/3284973/3549454/489fbc30-08c9-11e4-91f8-c6f90703b45a.png)
Thanks for your hard work!

**Comment by martimorta** [comment]
Just checked the askbot forum and they have the same problem...

**Comment by martimorta** [comment]
In fact, only resizing your screen the problem appears:
![askbot_shit_css](https://cloud.githubusercontent.com/assets/3284973/3549613/4a4599e4-08cc-11e4-9df5-74da38db59cb.png)

**Comment by martimorta** [comment]
These lines hide contents when the window has a maximum width, ugly UI trick...

``` css
(line 4487)
@media screen and (max-width: 800px){
    #ContentRight {
        display: none;
    }
}
(line 4589)
    .question-page .post-update-info br,
    .question-page .post-update-info .badge1,
    .question-page .post-update-info .badge2,
    .question-page .post-update-info .badge3,
    .question-page .post-update-info .gravatar,
    .question-page .post-update-info .reputation-score,
    .question-page .post-update-info .user-card,
    .question-page .post-update-info .badge-count {
        display: none;
    }
```

commenting this, the result is not consistent with the post design but at least shows the user, which would be enough to quickly ban bots from smaller devices (if the moderation page is shown properly)

``` css
    .question-page .post-update-info .badge-count {
        /*display: none;*/
    }
```

I hope this helps!
![fix-mierder](https://cloud.githubusercontent.com/assets/3284973/3550016/f6c501a4-08d2-11e4-8395-6eea2d4f6000.png)
